BMCP-2: Some basic folder and files
Eva-Platform/bmcp-website pull request #2
Opened 2021-06-15 09:13 UTC by nikhilsharma0025

## Description
- Added some components and pages folder and created basic components file like topbar, footer and routes

#### Modification
-added components  and pages folder 
-added  routes,footer , topbar file

2021-06-15 09:35 UTC, nik-1236789 commented on src/components/footer/footer.tsx
> +function footer() {
Consider starting the component name with capital alphabets and try using ES6 syntax (optional) for function creation along with  proper types (required) from "typescript" .

2021-06-15 09:35 UTC, nik-1236789 commented on src/components/topbar/topbar.tsx
> +function topbar() {
Same as in Footer component

2021-06-15 09:36 UTC, nik-1236789 commented on src/routes.tsx
> +        <Switch>
You need to wrap the routes inside a Router. Consider using BrowserRouter or HashRouter(preferred). Otherwise this won't work.

2021-06-15 09:37 UTC, nik-1236789 requested changes
Have a look on the points mentioned in the comments.

2021-06-15 11:42 UTC, 2SkeePeR2 commented on src/components/footer/footer.tsx
> +        <div>
Consider using ```React.Fragment``` for such components.

2021-06-15 11:43 UTC, 2SkeePeR2 requested changes

2021-06-15 11:43 UTC, 2SkeePeR2 commented on src/components/topbar/topbar.tsx
> +        <div>
```React.Fragment```

2021-06-15 11:43 UTC, 2SkeePeR2 commented on src/pages/home.tsx
> +        <div>
```React.Fragment```

2021-06-16 09:38 UTC, 2SkeePeR2 requested changes

2021-06-16 09:38 UTC, 2SkeePeR2 commented on src/index.js
> -  <React.StrictMode>
Don't remove this tag

2021-06-16 09:38 UTC, 2SkeePeR2 commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Why comment ?

2021-06-16 13:01 UTC, nik-1236789 approved these changes

2021-06-16 16:50 UTC, nik-1236789 approved these changes

2021-06-17 04:54 UTC, merged