BMCP-9: Topbar Component
Eva-Platform/bmcp-website pull request #4
Opened 2021-06-21 12:34 UTC by nikhilsharma0025

## Description
Adding topbar component using material and mobile-friendly also .

#### Modification
Topbar Component

2021-06-21 13:20 UTC, 2SkeePeR2 requested changes
Add a pic of the topbar before we can approve.

2021-06-21 13:20 UTC, 2SkeePeR2 commented on src/components/topbar/topbar.tsx
> +      <Menu keepMounted open={!!open} anchorEl={menuAnchorRef.current}  onClose={closeMenu} >
!!open ?

2021-06-21 15:08 UTC, nik-1236789 commented on src/components/topbar/topbar.tsx
> +      <Menu keepMounted open={!!open} anchorEl={menuAnchorRef.current}  onClose={closeMenu} >
remove double negation.

2021-06-21 15:09 UTC, nik-1236789 approved these changes

2021-06-21 15:18 UTC, nikhilsharma0025 commented
![2021-06-21 (1)](https://user-images.githubusercontent.com/61248874/122786410-e95b3a80-d2d1-11eb-9e65-2b18290c8e33.png)
![2021-06-21](https://user-images.githubusercontent.com/61248874/122786434-ef511b80-d2d1-11eb-8908-0b65c9eccfa2.png)

2021-06-28 22:49 UTC, 2SkeePeR2 approved these changes

2021-06-28 22:49 UTC, 2SkeePeR2 commented
GG :fire:

2021-06-29 14:53 UTC, merged