BMCP-5: About page
Eva-Platform/bmcp-website pull request #5
Opened 2021-06-27 19:41 UTC by nikhilsharma0025

## Description 
Added  About US Page 

#### Modification
Added about us component

2021-07-03 03:31 UTC, truelegion47 commented
@nikhilsharma0025 How much more time are we going to spend on this ?

2021-07-10 18:28 UTC, 2SkeePeR2 requested changes
Pictures are not be uploaded to Github. Although for now it's OK but after the website is finished, consider moving it to an online picture library, creating a link to it, and using its URL.

All pictures must be gitignored.

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/App.css
> +background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 1000'%3E%3Cg %3E%3Ccircle fill='%233afcff' cx='50' cy='0' r='50'/%3E%3Cg fill='%231bf3fe' %3E%3Cci
Why is it not styled?

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/App.tsx
> +          {/* <Route path='/srvices' component={Services} />
Comments ?

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/components/About/About.tsx
> +            <br></br>
Avoid using ```<br>```. Instead use styles like padding or margin to space and place objects.

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/components/About/About.tsx
> +                            <Card className={classes.svg}>
How can a className have ```.svg``` ? Please use it only as an extension and rename this.

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/components/About/About.tsx
> +                        </Grid>
Fix the styling

2021-07-10 18:28 UTC, 2SkeePeR2 commented on src/components/Home/Home.tsx
> +         </div>
Styling ?

2021-07-10 18:34 UTC, nik-1236789 commented on src/App.tsx
> +          <Route path='/footer' component={Footer} />
Footer isn't a Route.

2021-07-10 18:36 UTC, nik-1236789 commented on src/components/About/About.tsx
> +import manojWadwan from '../../images/manojWadwan.png'
For now this is fine but when you are finished with the website, lets host these images online and get their urls.

2021-07-10 18:38 UTC, nik-1236789 requested changes
Make the changes as discussed and do add a screenshot (on priority) of the work that is done here.

2021-07-11 00:46 UTC, nikhilsharma0025 commented on src/components/About/About.tsx
> +            <br></br>
Ohk

2021-07-11 08:23 UTC, nikhilsharma0025 commented
![2021-07-11](https://user-images.githubusercontent.com/61248874/125187840-31290e00-e24f-11eb-892d-392bec48f1dc.png)
![2021-07-11 (1)](https://user-images.githubusercontent.com/61248874/125187846-36865880-e24f-11eb-8e94-7ca5b3fd13a4.png)
![2021-07-11 (2)](https://user-images.githubusercontent.com/61248874/125187851-3ab27600-e24f-11eb-828e-6b3a0187296b.png)

2021-07-14 15:51 UTC, merged