BMCP-10 : Create Footer
Eva-Platform/bmcp-website pull request #6
Opened 2021-06-29 13:59 UTC by 11vartika

**Create Footer**

       Added  -
  1.  
![WhatsApp Image 2021-06-29 at 7 22 58 PM](https://user-images.githubusercontent.com/81799415/123810369-f5697c80-d90f-11eb-811b-3376f78895ec.jpeg)
![Screenshot from 2021-06-29 19-20-05](https://user-images.githubusercontent.com/81799415/123810408-fd292100-d90f-11eb-942d-bc636569ff18.png)
src / components/Footer/index.tsx
  2 . src / components/Footer/Footer.styles.css 

     Modified -
1.    App.tsx
 2.   routes.tsx

2021-06-29 16:06 UTC, nik-1236789 commented on src/routes.tsx
> +import { Footer } from "./components/Footer";
We don't want it in the router.This needs to be displayed irrespective of the route.

2021-06-29 16:06 UTC, nik-1236789 requested changes
Looks good. Just get the commented query sorted!

2021-06-30 03:35 UTC, 2SkeePeR2 commented on src/components/Topbar/Topbar.tsx
> +
Remove the file if not required

2021-06-30 03:38 UTC, 2SkeePeR2 requested changes

2021-06-30 03:38 UTC, 2SkeePeR2 commented on src/components/Topbar/Topbar.tsx
> +
What is the purpose of this file? If not required, then delete it.

2021-06-30 05:15 UTC, 11vartika commented on src/components/Topbar/Topbar.tsx
> +
okay

2021-06-30 07:07 UTC, nikhilsharma0025 commented on src/components/Topbar/Topbar.tsx
> +
just take the latest pull this will be fixed,then push that

2021-06-30 07:12 UTC, 11vartika commented on src/components/Topbar/Topbar.tsx
> +
okay

2021-07-01 09:44 UTC, 2SkeePeR2 approved these changes

2021-07-03 03:30 UTC, truelegion47 commented
@nik-1236789 @2SkeePeR2 Is this ready to go ?

2021-07-03 03:44 UTC, 2SkeePeR2 commented
> @nik-1236789 @2SkeePeR2 Is this ready to go ? 

Approved by me.... ASK @nik-1236789

2021-07-11 15:22 UTC, nik-1236789 reviewed
@nikhilsharma0025 @rccoding discuss with each other and replicate this work.

2021-07-11 15:26 UTC, nikhilsharma0025 commented
I will work on this thing

2021-07-12 07:08 UTC, closed without merging